language: php

php:
  - 7.0

services:
  - docker

before_install:
  - docker build -t l5app .
  - sleep 15
  - docker run -d --name db-lock-poc -v `pwd`:/var/www/html -v `pwd`/mysql_data:/var/lib/mysql -p 8000:80 l5app
  - docker logs db-lock-poc

install:
  - composer self-update
  - travis_retry composer install --no-interaction --no-scripts --prefer-source --dev

before_script:
  - TRAVIS=true
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - docker ps
  - wget http://localhost:8000/api -O welcome.json

matrix:
  fast_finish: true